app = "email-template-verifier" # Change this to your unique Fly app name

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "python:3.11-slim"

[env]

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443
